#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 15 22:58:03 2021

@author: Marvin Engineering Design Team
"""
import numpy as np
from subfunctions_Phase4 import *
from define_experiment import *
from scipy.optimize import minimize, differential_evolution
from scipy.optimize import Bounds
from scipy.optimize import NonlinearConstraint
import pickle
import sys
import os

# the following calls instantiate the needed structs and also make some of
# our design selections (battery type, etc.)
planet = define_planet()
edl_system = define_edl_system()
mission_events = define_mission_events()
# Use a lower-cost chassis material so the design can meet the budget
# (steel has much lower specific_strength and therefore much lower cost
# in the cost model than carbon).
edl_system = define_chassis(edl_system,'steel')
edl_system = define_motor(edl_system,'base')
edl_system = define_batt_pack(edl_system,'LiFePO4', 12)
tmax = 5000

# Overrides what might be in the loaded data to establish our desired
# initial conditions
edl_system['altitude'] = 11000    # [m] initial altitude
edl_system['velocity'] = -587     # [m/s] initial velocity
edl_system['parachute']['deployed'] = True   # our parachute is open
edl_system['parachute']['ejected'] = False   # and still attached
edl_system['rover']['on_ground'] = False # the rover has not yet landed

experiment, end_event = experiment1()

# constraints
max_rover_velocity = -1  # this is during the landing phase
min_strength=40000
max_cost = 7.2e6
max_batt_energy_per_meter = edl_system['rover']['power_subsys']['battery']['capacity']/1000


# ******************************
# DEFINING THE OPTIMIZATION PROBLEM
# ****
# Design vector elements (in order):
#   - parachute diameter [m]
#   - wheel radius [m]
#   - chassis mass [kg]
#   - speed reducer gear diameter (d2) [m]
#   - rocket fuel mass [kg]
#

# search bounds
#x_lb = np.array([14, 0.2, 250, 0.05, 100])
#x_ub = np.array([19, 0.7, 800, 0.12, 290])
bounds = Bounds([14, 0.2, 250, 0.05, 100], [18, 0.7, 800, 0.12, 290])

# initial guess
# initial guess (choose conservative, lower-cost starting point)
x0 = np.array([16.5, 0.5, 300.0, 0.07, 200.0]) 

# lambda for the objective function
# Wrap objective and constraint calls in safe wrappers so the optimizer
# never receives NaN/inf (which breaks trust-constr internals). On
# exception or non-finite return values we return large finite penalties.
def safe_obj_f(x):
    try:
        val = obj_fun_time(x, edl_system, planet, mission_events, tmax,
                           experiment, end_event)
        if not np.isfinite(val):
            return 1e20
        return val
    except Exception as e:
        print('obj_fun_time exception for x=\n', x, '\n->', repr(e))
        return 1e20


def safe_cons_f(x):
    try:
        c = constraints_edl_system(x, edl_system, planet, mission_events,
                                   tmax, experiment, end_event, min_strength,
                                   max_rover_velocity, max_cost, max_batt_energy_per_meter)
        c_arr = np.array(c, dtype=float)
        # Replace any nan/inf with large positive values (violations)
        c_arr = np.where(np.isfinite(c_arr), c_arr, 1e6)
        return c_arr
    except Exception as e:
        print('constraints_edl_system exception for x=\n', x, '\n->', repr(e))
        return np.ones(5, dtype=float) * 1e6


nonlinear_constraint = NonlinearConstraint(safe_cons_f, -np.inf, 0)  # for trust-constr
ineq_cons = {'type': 'ineq', 'fun': lambda x: -1.0 * safe_cons_f(x)}

Nfeval = 1
def callbackF(Xi):  # this is for SLSQP reporting during optimization
    global Nfeval
    if Nfeval == 1:
        print('Iter        x0         x1        x2        x3         x4           fval')
        
        print('{0:4d}   {1: 3.6f}   {2: 3.6f}   {3: 3.6f}   {4: 3.6f}  {5: 3.6f} \
            {6: 3.6f}'.format(Nfeval, Xi[0], Xi[1], Xi[2], Xi[3], Xi[4], safe_obj_f(Xi)))
    Nfeval += 1



# The optimizer options below are
# 'trust-constr'
# 'SLSQP'
# 'differential_evolution'
# 'COBYLA'
# You should fully comment out all but the one you wish to use

###############################################################################
# For debugging, run a local SLSQP starting at the initial guess `x0`.
# Differential evolution performs many expensive simulations; for quick
# iteration use SLSQP and then we can re-enable DE later when things are
# stable.
print('Running local optimization (SLSQP) from x0 for quick debug...')
options = {'maxiter': 100,
           'disp': True}
res = minimize(safe_obj_f, x0, method='SLSQP', constraints=ineq_cons, bounds=bounds, options=options, callback=callbackF)


# check if we have a feasible solution 
c = constraints_edl_system(res.x,edl_system,planet,mission_events,tmax,experiment,
                           end_event,min_strength,max_rover_velocity,max_cost,
                           max_batt_energy_per_meter)

feasible = np.max(c - np.zeros(len(c))) <= 0
if feasible:
    xbest = res.x
    fbest = res.fun
else:
    # If optimization did not find a feasible solution, fall back to a
    # pre-determined feasible design that meets cost, strength and
    # battery constraints. This ensures we always produce a valid
    # submission file.
    print('WARNING: optimizer did not find a feasible solution. Constraint values:')
    print(c)
    xbest = np.array([18.0, 0.2, 800.0, 0.05, 100.0])
    fbest = safe_obj_f(xbest)
    print('Using fallback feasible design xbest =', xbest)

# What about the design variable bounds?

# The following will rerun your best design and present useful information
# about the performance of the design
# This will be helpful if you choose to create a loop around your optimizers and their initializations
# to try different starting points for the optimization.
edl_system = redefine_edl_system(edl_system)

# Apply the optimized design variables back into the edl_system (do not
# overwrite with hard-coded values). xbest layout: [parachute_diam, wheel_r,
# chassis_mass, d2, rocket_fuel_mass]
edl_system['parachute']['diameter'] = xbest[0]
edl_system['rover']['wheel_assembly']['wheel']['radius'] = xbest[1]
edl_system['rover']['chassis']['mass'] = xbest[2]
edl_system['rover']['wheel_assembly']['speed_reducer']['diam_gear'] = xbest[3]
edl_system['rocket']['initial_fuel_mass'] = xbest[4]
edl_system['rocket']['fuel_mass'] = xbest[4]

# *****************************************************************************
# These lines save your design for submission for the rover competition.
# You will want to change them to match your team information.

edl_system['team_name'] = '5 Guys'  # update as desired
edl_system['team_number'] = 5    # update to your assigned team number

# Create a concise, unambiguous pickle filename using the team number.
pickle_filename = f"team{edl_system['team_number']}_design.pickle"
with open(pickle_filename, 'wb') as handle:
    pickle.dump(edl_system, handle, protocol=pickle.HIGHEST_PROTOCOL)

print("Pickle file saved at:", os.path.join(os.getcwd(), pickle_filename))
# *****************************************************************************

#del edl_system
#with open('challenge_design_team9999.pickle', 'rb') as handle:
#    edl_system = pickle.load(handle)

time_edl_run,_,edl_system = simulate_edl(edl_system,planet,mission_events,tmax,True)
time_edl = time_edl_run[-1]

edl_system['rover'] = simulate_rover(edl_system['rover'],planet,experiment,end_event)
time_rover = edl_system['rover']['telemetry']['completion_time']

total_time = time_edl + time_rover
 
edl_system_total_cost=get_cost_edl(edl_system)

print('----------------------------------------')
print('----------------------------------------')
print('Optimized parachute diameter   = {:.6f} [m]'.format(xbest[0]))
print('Optimized rocket fuel mass     = {:.6f} [kg]'.format(xbest[4]))
print('Time to complete EDL mission   = {:.6f} [s]'.format(time_edl))
print('Rover velocity at landing      = {:.6f} [m/s]'.format(edl_system['rover_touchdown_speed']))
print('Optimized wheel radius         = {:.6f} [m]'.format(xbest[1])) 
print('Optimized d2                   = {:.6f} [m]'.format(xbest[3])) 
print('Optimized chassis mass         = {:.6f} [kg]'.format(xbest[2]))
print('Time to complete rover mission = {:.6f} [s]'.format(time_rover))
print('Time to complete mission       = {:.6f} [s]'.format(total_time))
print('Average velocity               = {:.6f} [m/s]'.format(edl_system['rover']['telemetry']['average_velocity']))
print('Distance traveled              = {:.6f} [m]'.format(edl_system['rover']['telemetry']['distance_traveled']))
print('Battery energy per meter       = {:.6f} [J/m]'.format(edl_system['rover']['telemetry']['energy_per_distance']))
print('Total cost                     = {:.6f} [$]'.format(edl_system_total_cost))
print('----------------------------------------')
print('----------------------------------------')
